#!/usr/bin/env bash

set -o errexit

main() {

  cd /home/travis/.rvm/bin
  # DPL installing ruby-2.7.8
  rvm pkg install openssl
  rvm install ruby-2.7.8 --with-openssl-dir=$HOME/.rvm/usr
  rvm use --default ruby-2.7.8
}

main "$@"
