#!/usr/bin/env bash
  main() {
    if [ "$1" = "run" ]; then
        shift
        command docker run -t -v /proc/cpuinfo:/proc/cpuinfo:rw -v /proc/meminfo:/proc/meminfo:rw -v /proc/stat:/proc/stat:rw "$@"
    else
        command docker "$@"
    fi
}

main "$@";
