#!/usr/bin/env bash

set -o errexit
set -o xtrace

main() {

  # Cosign installation
  local COSIGN_VERSION="1.10.1"
  wget -q "https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-${COSIGN_VERSION}.x86_64.rpm"    
  sudo mv cosign-"${COSIGN_VERSION}".x86_64.rpm /usr/local/bin/cosign
  sudo chmod +x /usr/local/bin/cosign
  cosign version

  # Rekor-cli installtion
  local REKOR_VERSION="v0.10.0"
  curl -O "https://github.com/sigstore/rekor/releases/download/${REKOR_VERSION}/rekor-cli-linux-${TRAVIS_CPU_ARCH}"
  sudo mv rekor-cli-linux-"${TRAVIS_CPU_ARCH}" /usr/local/bin/rekor-cli
  sudo chmod +x /usr/local/bin/rekor-cli
  rekor-cli version

  sudo mv 1.10.1.amd64 /usr/local/bin/cosign
  sudo chmod +x /usr/local/bin/cosign
  cosign version

}

main "$@"