#!/usr/bin/env bash

set -o errexit
set -o xtrace

main() {

    wget https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz --quiet --directory-prefix /home --output-document=jdk.tar.gz --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 --continue
    sudo tar --extract --file jdk.tar.gz -C /home
    export JAVA_HOME=$(cd "/home"; pwd)
    export PATH=${JAVA_HOME}/bin:$PATH
    #export JAVA_HOME=/home/jdk-16.0.2+7/
    #export PATH=$PATH:$JAVA_HOME/bin
    EOF



}

main "$@"