#!/usr/bin/env bash

set -o errexit
set -o xtrace

main() {

    wget https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_linux-x64_bin.tar.gz --quiet --directory-prefix $HOME --output-document=jdk.tar.gz --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 --continue
    sudo tar --extract --file jdk.tar.gz -C $HOME
    export JAVA_HOME=$(cd $HOME; pwd)
    export PATH=${JAVA_HOME}/bin:$PATH
    #export JAVA_HOME=/home/jdk-16.0.2+7/
    #export PATH=$PATH:$JAVA_HOME/bin
}

main "$@"